-- AUTO-GENERATED by LuaFactorySchemaRegistry. Do not edit by hand.
-- Source of truth: hob:: bind_factory_schema(...) calls in lua_bind_*.cpp.

_G.__factory_schemas = {
    AnimationClips = {
        define = "DefineAnimationClip",
        lua_type = "AnimationClip",
        fields = {
            { name = "textures" },
            { name = "fps" },
            { name = "looping" },
        },
    },
    Shaders = {
        define = "DefineShader",
        lua_type = "Shader",
        fields = {
            { name = "path" },
            { name = "blend" },
            { name = "cull" },
            { name = "defaults" },
        },
    },
    Materials = {
        define = "DefineMaterial",
        lua_type = "Material",
        fields = {
            { name = "shader" },
            { name = "textures" },
        },
    },
}
