-- AUTO-GENERATED by LuaPathSchemaRegistry. Do not edit by hand.
-- Source of truth: hob:: bind_path_schema(...) calls in lua_bind_assets.cpp.

_G.__path_schemas = {
    { registry = "Assets", define = "DefineAsset", type_label = "Asset" },
    { registry = "Textures", define = "DefineTexture", type_label = "Texture" },
}
