---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_shader_params_meta. Do not edit by hand.
-- Source of truth: the SPIR-V reflection of each shader's `Material` cbuffer.
-- One class per shader lists its settable params (and texture bindings). Annotate a
-- DefineMaterial assignment to get autocomplete + type checks for that shader's params:
--   ---@type MaterialParams.Outline
--   DefineMaterial.WhiteOutline = { shader = Shaders.Outline, outline_color = Color.white() }

---@class MaterialParams.Distort
---@field shader? Shader
---@field tint? Color
---@field alpha_threshold? number
---@field distort_strength? number
---@field distort_speed? number
---@field textures? MaterialTextures.Distort

---@class MaterialTextures.Distort
---@field distort_tex? Texture|string

---@class MaterialParams.Outline
---@field shader? Shader
---@field tint? Color
---@field outline_color? Color
---@field outline_width? number
---@field alpha_threshold? number

---@class MaterialParams.Psychedelic
---@field shader? Shader
---@field tint? Color
---@field alpha_threshold? number

---@class MaterialParams.Sprite
---@field shader? Shader
---@field tint? Color
---@field alpha_threshold? number

