---@meta
-- AUTO-GENERATED by LuaMetaRegistry. Do not edit by hand.
-- Source of truth: hob::LuaScriptSystem::register_bindings().

-- Math
---@class Math
---@field PI number
---@field EPSILON number
---@field DEG_TO_RAD number
---@field RAD_TO_DEG number
---@field MIN_INTEGER integer
---@field MAX_INTEGER integer
---@field MIN_NUMBER number
---@field MAX_NUMBER number
Math = {}

---@param angle_deg number
---@return number
function Math.normalize_angle(angle_deg) end

---@param a number
---@param b number
---@param t number
---@return number
function Math.lerp(a, b, t) end

---@param a_deg number
---@param b_deg number
---@param t number
---@return number
function Math.lerp_angle(a_deg, b_deg, t) end

-- Camera
---@class Camera
Camera = {}

---@return Entity?
function Camera.get_active() end

---@return number
function Camera.get_pixels_per_meter() end

---@param value number
function Camera.set_pixels_per_meter(value) end

---@return number
function Camera.get_zoom() end

---@param multiplier number
function Camera.set_zoom(multiplier) end

---@param world_pos Vector2
---@return Vector2
function Camera.world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Vector2
function Camera.screen_to_world(screen_pos) end

---@return Vector2
function Camera.get_position() end

---@param position Vector2
function Camera.set_position(position) end

-- Timer
---@class Timer
Timer = {}

---@return integer
function Timer.get_fps() end

---@param fps integer
function Timer.set_fps(fps) end

---@return number
function Timer.get_time_scale() end

---@param scale number
function Timer.set_time_scale(scale) end

---@return number
function Timer.get_delta_time() end

---@return number
function Timer.get_game_time() end

---@return number
function Timer.get_real_time() end

-- Input
---@class Input
Input = {}

---@return Vector2
function Input.get_mouse_screen_position() end

---@return boolean
function Input.is_gamepad_connected() end

-- UI
---@class UI
UI = {}

---@param world_pos Vector2
---@return Vector2
function UI.world_to_ui(world_pos) end

---@param path string
---@return integer
function UI.load_document(path) end

---@param document integer
function UI.unload_document(document) end

---@param document integer
function UI.show_document(document) end

---@param document integer
function UI.hide_document(document) end

---@param document integer
---@param element_id string
---@return integer
function UI.get_element(document, element_id) end

---@param element integer
---@param property string
---@return string
function UI.get_element_property(element, property) end

---@param element integer
---@param property string
---@param value string
function UI.set_element_property(element, property, value) end

---@param element integer
---@return Vector2
function UI.get_element_position(element) end

---@param element integer
---@param position Vector2
function UI.set_element_position(element, position) end

---@param element integer
---@param event string
---@param fn fun()
---@return integer
function UI.add_event_listener(element, event, fn) end

---@param listener integer
function UI.remove_event_listener(listener) end

---@param name string
---@param fields table<string, boolean|integer|number|string>
---@return integer
function UI.create_model(name, fields) end

---@param model integer
function UI.destroy_model(model) end

---@param model integer
---@param field string
---@return boolean|integer|number|string
function UI.get(model, field) end

---@param model integer
---@param field string
---@param value boolean|integer|number|string
function UI.set(model, field, value) end

---@param model integer
---@param event string
---@param fn fun()
function UI.bind_event(model, event, fn) end

-- Physics
---@class Physics
Physics = {}

---@param origin Vector2
---@param direction Vector2
---@param distance number
---@param layer_mask integer?
---@return RaycastHit
function Physics.raycast(origin, direction, distance, layer_mask) end

---@param origin Vector2
---@param direction Vector2
---@param distance number
---@param layer_mask integer?
---@return RaycastHit[]
function Physics.raycast_all(origin, direction, distance, layer_mask) end

-- Audio
---@class Audio
Audio = {}

---@param clip AudioClip
---@param volume number?
function Audio.play_oneshot(clip, volume) end

---@return number
function Audio.get_master_volume() end

---@param volume number
function Audio.set_master_volume(volume) end

-- EntitySpawner
---@class EntitySpawner
EntitySpawner = {}

---@return Entity
function EntitySpawner.spawn_entity_c() end

---@param entity Entity
function EntitySpawner.destroy_entity_c(entity) end

---@param id integer
---@return Entity
function EntitySpawner.get_entity(id) end

---@param fn fun(entity: Entity)
function EntitySpawner.for_each(fn) end

-- Scripts
---@class Scripts
Scripts = {}

---@param relative_path string
---@return boolean
function Scripts.run_engine_file(relative_path) end

---@param relative_path string
---@param excludes string[]?
---@return boolean
function Scripts.run_engine_folder(relative_path, excludes) end

---@param relative_path string
---@return boolean
function Scripts.run_project_file(relative_path) end

---@param relative_path string
---@param excludes string[]?
---@return boolean
function Scripts.run_project_folder(relative_path, excludes) end

-- Debug
---@class Debug
Debug = {}

---@param message string
---@param color Color?
---@param duration number?
---@param log boolean?
function Debug.print(message, color, duration, log) end

---@param from Vector2
---@param to Vector2
---@param color Color?
---@param duration number?
---@param thickness number?
function Debug.draw_line(from, to, color, duration, thickness) end

---@param center Vector2
---@param radius number
---@param color Color?
---@param duration number?
---@param thickness number?
---@param segments integer?
function Debug.draw_circle(center, radius, color, duration, thickness, segments) end

-- Log
---@class Log
Log = {}

---@vararg any
function Log.info(...) end

---@vararg any
function Log.error(...) end

-- BodyType
---@enum BodyType
BodyType = {
    Static = 0,
    Dynamic = 1,
    Kinematic = 2,
}

-- InputEventType
---@enum InputEventType
InputEventType = {
    Axis = 0,
    Pressed = 1,
    Released = 2,
}

-- Vector2
---@class Vector2
---@field x number
---@field y number
---@operator add(Vector2): Vector2
---@operator sub(Vector2): Vector2
---@operator unm: Vector2
---@operator mul(number): Vector2
---@operator div(number): Vector2
---@overload fun(): Vector2
---@overload fun(x: number, y: number): Vector2
local Vector2 = {}

---@return number
function Vector2:length() end

---@return number
function Vector2:length_sqr() end

---@return Vector2
function Vector2:normalized() end

---@return Vector2
function Vector2.zero() end

---@return Vector2
function Vector2.one() end

---@return Vector2
function Vector2.left() end

---@return Vector2
function Vector2.right() end

---@return Vector2
function Vector2.up() end

---@return Vector2
function Vector2.down() end

---@param a Vector2
---@param b Vector2
---@return number
function Vector2.dot(a, b) end

---@param a Vector2
---@param b Vector2
---@return number
function Vector2.distance(a, b) end

---@param a Vector2
---@param b Vector2
---@param t number
---@return Vector2
function Vector2.lerp(a, b, t) end

---@param point Vector2
---@param pivot Vector2
---@param radians number
---@return Vector2
function Vector2.rotate_around(point, pivot, radians) end

_G.Vector2 = Vector2

-- AABB
---@class AABB
---@field center Vector2
---@field extents Vector2
---@overload fun(center: Vector2, extents: Vector2): AABB
local AABB = {}

---@return Vector2
function AABB:min() end

---@return Vector2
function AABB:max() end

---@return Vector2
function AABB:size() end

_G.AABB = AABB

-- Capsule
---@class Capsule
---@field center_a Vector2
---@field center_b Vector2
---@field radius number
---@overload fun(center_a: Vector2, center_b: Vector2, radius: number): Capsule
local Capsule = {}

---@return number
function Capsule:get_height() end

_G.Capsule = Capsule

-- Circle
---@class Circle
---@field center Vector2
---@field radius number
---@overload fun(center: Vector2, radius: number): Circle
local Circle = {}

_G.Circle = Circle

-- Color
---@class Color
---@field r number
---@field g number
---@field b number
---@field a number
---@overload fun(): Color
---@overload fun(r: number, g: number, b: number): Color
---@overload fun(r: number, g: number, b: number, a: number): Color
local Color = {}

---@return Color
function Color.black() end

---@return Color
function Color.white() end

---@return Color
function Color.gray() end

---@return Color
function Color.red() end

---@return Color
function Color.green() end

---@return Color
function Color.blue() end

---@return Color
function Color.yellow() end

---@return Color
function Color.magenta() end

---@return Color
function Color.cyan() end

---@return Color
function Color.orange() end

_G.Color = Color

-- Entity
---@class Entity
local Entity = {}

---@return integer
function Entity:get_id() end

---@return boolean
function Entity:is_valid() end

---@return boolean
function Entity:is_in_play() end

---@return boolean
function Entity:is_ticking() end

---@param ticking boolean
function Entity:set_ticking(ticking) end

---@param class_name string
---@return LuaComponent?
function Entity:add_lua_component(class_name) end

---@return TransformComponent?
function Entity:get_transform() end

---@return RigidbodyComponent?
function Entity:get_rigidbody() end

---@return CharacterBodyComponent?
function Entity:get_character_body() end

---@return BoxColliderComponent?
function Entity:get_box_collider() end

---@return CapsuleColliderComponent?
function Entity:get_capsule_collider() end

---@return CircleColliderComponent?
function Entity:get_circle_collider() end

---@return InputComponent?
function Entity:get_input() end

---@return SpriteComponent?
function Entity:get_sprite() end

---@return SpriteAnimatorComponent?
function Entity:get_sprite_animator() end

---@return CameraComponent?
function Entity:get_camera() end

---@return AudioComponent?
function Entity:get_audio() end

---@param class_name string
---@return LuaComponent?
function Entity:get_lua_component(class_name) end

---@return LuaComponent[]
function Entity:get_lua_components() end

---@return Component[]
function Entity:get_components() end

---@return RigidbodyComponent?
function Entity:add_rigidbody() end

---@return CharacterBodyComponent?
function Entity:add_character_body() end

---@return BoxColliderComponent?
function Entity:add_box_collider() end

---@return CapsuleColliderComponent?
function Entity:add_capsule_collider() end

---@return CircleColliderComponent?
function Entity:add_circle_collider() end

---@return InputComponent?
function Entity:add_input() end

---@return SpriteComponent?
function Entity:add_sprite() end

---@return SpriteAnimatorComponent?
function Entity:add_sprite_animator() end

---@return CameraComponent?
function Entity:add_camera() end

---@return AudioComponent?
function Entity:add_audio() end

_G.Entity = Entity

-- Component
---@class Component
local Component = {}

---@return Entity
function Component:get_entity() end

_G.Component = Component

-- TransformComponent
---@class TransformComponent : Component
local TransformComponent = {}

---@return Vector2
function TransformComponent:get_position() end

---@param position Vector2
function TransformComponent:set_position(position) end

---@return number
function TransformComponent:get_rotation() end

---@param radians number
function TransformComponent:set_rotation(radians) end

---@return Vector2
function TransformComponent:get_scale() end

---@param scale Vector2
function TransformComponent:set_scale(scale) end

---@return Vector2
function TransformComponent:get_local_position() end

---@param position Vector2
function TransformComponent:set_local_position(position) end

---@return number
function TransformComponent:get_local_rotation() end

---@param radians number
function TransformComponent:set_local_rotation(radians) end

---@return Vector2
function TransformComponent:get_local_scale() end

---@param scale Vector2
function TransformComponent:set_local_scale(scale) end

---@return TransformComponent?
function TransformComponent:get_parent() end

---@param parent TransformComponent?
---@param keep_world_transform boolean?
function TransformComponent:set_parent(parent, keep_world_transform) end

---@return TransformComponent[]
function TransformComponent:get_children() end

---@return boolean
function TransformComponent:get_interpolate_physics() end

---@param value boolean
function TransformComponent:set_interpolate_physics(value) end

_G.TransformComponent = TransformComponent

-- RigidbodyComponent
---@class RigidbodyComponent : Component
local RigidbodyComponent = {}

---@return BodyType
function RigidbodyComponent:get_body_type() end

---@param body_type BodyType
function RigidbodyComponent:set_body_type(body_type) end

---@return boolean
function RigidbodyComponent:has_fixed_rotation() end

---@param fixed boolean
function RigidbodyComponent:set_fixed_rotation(fixed) end

---@return Vector2
function RigidbodyComponent:get_velocity() end

---@param velocity Vector2
function RigidbodyComponent:set_velocity(velocity) end

---@return Vector2
function RigidbodyComponent:get_position() end

---@param position Vector2
function RigidbodyComponent:set_position(position) end

---@return number
function RigidbodyComponent:get_rotation() end

---@param radians number
function RigidbodyComponent:set_rotation(radians) end

_G.RigidbodyComponent = RigidbodyComponent

-- CharacterBodyComponent
---@class CharacterBodyComponent : Component
local CharacterBodyComponent = {}

---@return integer
function CharacterBodyComponent:get_collision_layer() end

---@param layer integer
function CharacterBodyComponent:set_collision_layer(layer) end

---@return integer
function CharacterBodyComponent:get_collision_mask() end

---@param mask integer
function CharacterBodyComponent:set_collision_mask(mask) end

---@return integer
function CharacterBodyComponent:get_solver_ignore_mask() end

---@param mask integer
function CharacterBodyComponent:set_solver_ignore_mask(mask) end

---@return Capsule
function CharacterBodyComponent:get_capsule() end

---@param capsule Capsule
function CharacterBodyComponent:set_capsule(capsule) end

---@param velocity Vector2
---@param fixed_dt number
function CharacterBodyComponent:move_and_slide(velocity, fixed_dt) end

---@return Vector2
function CharacterBodyComponent:get_velocity() end

---@param velocity Vector2
function CharacterBodyComponent:set_velocity(velocity) end

---@return Vector2
function CharacterBodyComponent:get_position() end

---@param position Vector2
function CharacterBodyComponent:set_position(position) end

---@return number
function CharacterBodyComponent:get_rotation() end

---@param radians number
function CharacterBodyComponent:set_rotation(radians) end

_G.CharacterBodyComponent = CharacterBodyComponent

-- ColliderComponent
---@class ColliderComponent : Component
local ColliderComponent = {}

---@return number
function ColliderComponent:get_density() end

---@param density number
function ColliderComponent:set_density(density) end

---@return number
function ColliderComponent:get_friction() end

---@param friction number
function ColliderComponent:set_friction(friction) end

---@return number
function ColliderComponent:get_bounciness() end

---@param bounciness number
function ColliderComponent:set_bounciness(bounciness) end

---@return integer
function ColliderComponent:get_collision_layer() end

---@param layer integer
function ColliderComponent:set_collision_layer(layer) end

---@return integer
function ColliderComponent:get_collision_mask() end

---@param mask integer
function ColliderComponent:set_collision_mask(mask) end

---@return boolean
function ColliderComponent:is_trigger() end

---@param trigger boolean
function ColliderComponent:set_trigger(trigger) end

_G.ColliderComponent = ColliderComponent

-- BoxColliderComponent
---@class BoxColliderComponent : ColliderComponent
local BoxColliderComponent = {}

---@return AABB
function BoxColliderComponent:get_aabb() end

---@param aabb AABB
function BoxColliderComponent:set_aabb(aabb) end

---@return AABB
function BoxColliderComponent:get_scaled_aabb() end

_G.BoxColliderComponent = BoxColliderComponent

-- CapsuleColliderComponent
---@class CapsuleColliderComponent : ColliderComponent
local CapsuleColliderComponent = {}

---@return Capsule
function CapsuleColliderComponent:get_capsule() end

---@param capsule Capsule
function CapsuleColliderComponent:set_capsule(capsule) end

---@return Capsule
function CapsuleColliderComponent:get_scaled_capsule() end

_G.CapsuleColliderComponent = CapsuleColliderComponent

-- CircleColliderComponent
---@class CircleColliderComponent : ColliderComponent
local CircleColliderComponent = {}

---@return Circle
function CircleColliderComponent:get_circle() end

---@param circle Circle
function CircleColliderComponent:set_circle(circle) end

---@return Circle
function CircleColliderComponent:get_scaled_circle() end

_G.CircleColliderComponent = CircleColliderComponent

-- InputComponent
---@class InputComponent : Component
local InputComponent = {}

---@param name string
---@param fn fun(value: number)
---@return integer
function InputComponent:bind_axis(name, fn) end

---@param name string
---@param id integer
function InputComponent:unbind_axis(name, id) end

---@param name string
---@param type InputEventType
---@param fn fun()
---@return integer
function InputComponent:bind_action(name, type, fn) end

---@param name string
---@param id integer
function InputComponent:unbind_action(name, id) end

function InputComponent:clear_all_bindings() end

_G.InputComponent = InputComponent

-- SpriteComponent
---@class SpriteComponent : Component
local SpriteComponent = {}

---@return Texture?
function SpriteComponent:get_texture() end

---@param path_or_texture string|Texture|nil
function SpriteComponent:set_texture(path_or_texture) end

function SpriteComponent:clear_texture() end

---@return Material?
function SpriteComponent:get_material() end

---@param material Material?
function SpriteComponent:set_material(material) end

---@return Vector2
function SpriteComponent:get_pivot() end

---@param pivot Vector2
function SpriteComponent:set_pivot(pivot) end

---@return Vector2
function SpriteComponent:get_scale() end

---@param scale Vector2
function SpriteComponent:set_scale(scale) end

---@return integer
function SpriteComponent:get_z_index() end

---@param z_index integer
function SpriteComponent:set_z_index(z_index) end

---@return integer
function SpriteComponent:get_pixels_per_meter() end

---@param value integer
function SpriteComponent:set_pixels_per_meter(value) end

_G.SpriteComponent = SpriteComponent

-- AnimationClip
---@class AnimationClip
---@overload fun(config: table): AnimationClip
local AnimationClip = {}

---@return number
function AnimationClip:get_fps() end

---@return boolean
function AnimationClip:get_looping() end

---@return integer
function AnimationClip:get_frame_count() end

_G.AnimationClip = AnimationClip

-- SpriteAnimatorComponent
---@class SpriteAnimatorComponent : Component
local SpriteAnimatorComponent = {}

---@param name string
---@param clip AnimationClip?
function SpriteAnimatorComponent:add_clip(name, clip) end

function SpriteAnimatorComponent:clear_clips() end

---@param name string
function SpriteAnimatorComponent:set_default_clip(name) end

---@return string
function SpriteAnimatorComponent:get_default_clip() end

---@return string
function SpriteAnimatorComponent:get_current_clip() end

---@return integer
function SpriteAnimatorComponent:get_current_frame() end

---@param name string
function SpriteAnimatorComponent:play(name) end

function SpriteAnimatorComponent:resume() end

function SpriteAnimatorComponent:pause() end

function SpriteAnimatorComponent:stop() end

---@return boolean
function SpriteAnimatorComponent:is_playing() end

---@return table<string, AnimationClip>
function SpriteAnimatorComponent:get_clips() end

---@param clips table<string, AnimationClip>
function SpriteAnimatorComponent:set_clips(clips) end

_G.SpriteAnimatorComponent = SpriteAnimatorComponent

-- CameraComponent
---@class CameraComponent : Component
local CameraComponent = {}

---@return number
function CameraComponent:get_pixels_per_meter() end

---@param value number
function CameraComponent:set_pixels_per_meter(value) end

---@return number
function CameraComponent:get_zoom() end

---@param multiplier number
function CameraComponent:set_zoom(multiplier) end

---@param world_pos Vector2
---@return Vector2
function CameraComponent:world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Vector2
function CameraComponent:screen_to_world(screen_pos) end

_G.CameraComponent = CameraComponent

-- AudioComponent
---@class AudioComponent : Component
local AudioComponent = {}

function AudioComponent:play() end

function AudioComponent:stop() end

---@return boolean
function AudioComponent:is_playing() end

---@return AudioClip?
function AudioComponent:get_clip() end

---@param clip AudioClip?
function AudioComponent:set_clip(clip) end

---@return number
function AudioComponent:get_volume() end

---@param volume number
function AudioComponent:set_volume(volume) end

---@return boolean
function AudioComponent:is_looping() end

---@param looping boolean
function AudioComponent:set_looping(looping) end

---@return boolean
function AudioComponent:is_spatial() end

---@param spatial boolean
function AudioComponent:set_spatial(spatial) end

---@return number
function AudioComponent:get_max_distance() end

---@param max_distance number
function AudioComponent:set_max_distance(max_distance) end

---@return boolean
function AudioComponent:get_autoplay() end

---@param autoplay boolean
function AudioComponent:set_autoplay(autoplay) end

_G.AudioComponent = AudioComponent

-- Texture
---@class Texture
---@overload fun(config: table): Texture
local Texture = {}

---@return integer
function Texture:get_width() end

---@return integer
function Texture:get_height() end

---@return string
function Texture:get_path() end

_G.Texture = Texture

-- Shader
---@class Shader
---@overload fun(config: table): Shader
local Shader = {}

_G.Shader = Shader

-- Material
---@class Material
---@overload fun(config: table): Material
local Material = {}

---@return string
function Material:get_name() end

---@param name string
function Material:set_name(name) end

---@param name string
---@return any
function Material:get_param(name) end

---@param name string
---@param value any
function Material:set_param(name, value) end

---@return Material?
function Material:clone() end

_G.Material = Material

-- RaycastHit
---@class RaycastHit
---@field collider ColliderComponent?
---@field point Vector2
---@field normal Vector2
---@field distance number
---@field hit boolean
---@field entity Entity?
local RaycastHit = {}

_G.RaycastHit = RaycastHit

-- AudioClip
---@class AudioClip
---@overload fun(config: table): AudioClip
local AudioClip = {}

---@return string
function AudioClip:get_path() end

_G.AudioClip = AudioClip

