---@meta
-- AUTO-GENERATED by LuaMetaRegistry. Do not edit by hand.
-- Source of truth: hob::LuaScriptSystem::register_bindings().

-- FileExtension
---@class FileExtension
---@field LUA string
---@field SCENE string
---@field PREFAB string
---@field MATERIAL string
---@field ANIMATION_CLIP string
---@field SHADER string
---@field META string
---@field MESH string
FileExtension = {}

-- DefRegistry
---@class DefRegistry
---@field SCENES string
---@field ENTITIES string
---@field COMPONENTS string
---@field TEXTURES string
---@field SHADERS string
---@field MATERIALS string
---@field ANIMATION_CLIPS string
---@field AUDIO_CLIPS string
---@field MESHES string
DefRegistry = {}

-- SceneKey
---@class SceneKey
---@field POSE_OVERRIDES string
---@field CPP_OVERRIDES string
---@field LUA_OVERRIDES string
SceneKey = {}

-- PrefabKey
---@class PrefabKey
---@field TICKING string
---@field LUA_COMPONENTS string
---@field LUA_FIELDS string
PrefabKey = {}

-- SpaceKey
---@class SpaceKey
---@field KEY string
---@field SPACE_2D string
---@field SPACE_3D string
SpaceKey = {}

-- TransformKey3D
---@class TransformKey3D
---@field SECTION string
---@field POSITION string
---@field ROTATION string
---@field ROTATION_DEG string
---@field SCALE string
TransformKey3D = {}

-- TransformKey
---@class TransformKey
---@field SECTION string
---@field POSITION string
---@field ROTATION string
---@field ROTATION_DEG string
---@field SCALE string
TransformKey = {}

-- FieldType
---@class FieldType
---@field INT string
---@field FLOAT string
---@field BOOL string
---@field STRING string
---@field VECTOR2 string
---@field VECTOR3 string
---@field QUATERNION string
---@field EULER_DEG string
---@field COLOR string
---@field ANGLE string
---@field ENUM string
---@field BITMASK string
---@field TEXTURE string
---@field MATERIAL string
---@field ANIMATION_CLIP string
---@field AUDIO_CLIP string
---@field MESH string
---@field AABB string
---@field AABB3 string
---@field CAPSULE string
---@field CIRCLE string
---@field OTHER string
FieldType = {}

-- Math
---@class Math
---@field PI number
---@field EPSILON number
---@field DEG_TO_RAD number
---@field RAD_TO_DEG number
---@field MIN_INT64 integer
---@field MAX_INT64 integer
---@field MIN_FLOAT number
---@field MAX_FLOAT number
---@field MIN_DOUBLE number
---@field MAX_DOUBLE number
Math = {}

---@param angle_deg number
---@return number
function Math.normalize_angle_deg(angle_deg) end

---@param angle_rad number
---@return number
function Math.wrap_angle_rad(angle_rad) end

---@param a number
---@param b number
---@param t number
---@return number
function Math.lerp(a, b, t) end

---@param a_deg number
---@param b_deg number
---@param t number
---@return number
function Math.lerp_angle(a_deg, b_deg, t) end

---@param a number
---@param b number
---@param epsilon number?
---@return boolean
function Math.approx_equal(a, b, epsilon) end

-- Camera
---@class Camera
Camera = {}

---@return Entity?
function Camera.get_active() end

---@return integer
function Camera.get_pixels_per_meter() end

---@param value integer
function Camera.set_pixels_per_meter(value) end

---@return number
function Camera.get_zoom() end

---@param multiplier number
function Camera.set_zoom(multiplier) end

---@param world_pos Vector2
---@return Vector2
function Camera.world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Vector2
function Camera.screen_to_world(screen_pos) end

---@return Vector2
function Camera.get_position() end

---@param position Vector2
function Camera.set_position(position) end

-- Camera3D
---@class Camera3D
Camera3D = {}

---@return Entity?
function Camera3D.get_active() end

---@return number
function Camera3D.get_fov_deg() end

---@param value number
function Camera3D.set_fov_deg(value) end

---@param world_pos Vector3
---@return Vector2?
function Camera3D.world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Ray
function Camera3D.screen_to_ray(screen_pos) end

---@return Vector3
function Camera3D.get_position() end

---@param position Vector3
function Camera3D.set_position(position) end

-- Timer
---@class Timer
Timer = {}

---@return integer
function Timer.get_fps() end

---@param fps integer
function Timer.set_fps(fps) end

---@return number
function Timer.get_time_scale() end

---@param scale number
function Timer.set_time_scale(scale) end

---@return number
function Timer.get_delta_time() end

---@return number
function Timer.get_game_time() end

---@return number
function Timer.get_real_time() end

-- Input
---@class Input
Input = {}

---@return Vector2
function Input.get_mouse_screen_position() end

---@return boolean
function Input.is_mouse_over_game_window() end

---@return boolean
function Input.is_gamepad_connected() end

-- UI
---@class UI
UI = {}

---@param world_pos Vector2
---@return Vector2
function UI.world_to_ui(world_pos) end

---@param path string
---@return integer
function UI.load_document(path) end

---@param document integer
function UI.unload_document(document) end

---@param document integer
function UI.show_document(document) end

---@param document integer
function UI.hide_document(document) end

---@param document integer
---@param element_id string
---@return integer
function UI.get_element(document, element_id) end

---@param element integer
---@param property string
---@return string
function UI.get_element_property(element, property) end

---@param element integer
---@param property string
---@param value string
function UI.set_element_property(element, property, value) end

---@param element integer
---@return Vector2
function UI.get_element_position(element) end

---@param element integer
---@param position Vector2
function UI.set_element_position(element, position) end

---@param element integer
---@param event string
---@param fn fun()
---@return integer
function UI.add_event_listener(element, event, fn) end

---@param listener integer
function UI.remove_event_listener(listener) end

---@param name string
---@param fields table<string, boolean|integer|number|string>
---@return integer
function UI.create_model(name, fields) end

---@param model integer
function UI.destroy_model(model) end

---@param model integer
---@param field string
---@return boolean|integer|number|string
function UI.get(model, field) end

---@param model integer
---@param field string
---@param value boolean|integer|number|string
function UI.set(model, field, value) end

---@param model integer
---@param event string
---@param fn fun()
function UI.bind_event(model, event, fn) end

-- Physics
---@class Physics
Physics = {}

---@param origin Vector2
---@param direction Vector2
---@param distance number
---@param layer_mask integer?
---@return RaycastHit
function Physics.raycast(origin, direction, distance, layer_mask) end

---@param origin Vector2
---@param direction Vector2
---@param distance number
---@param layer_mask integer?
---@return RaycastHit[]
function Physics.raycast_all(origin, direction, distance, layer_mask) end

-- Physics3D
---@class Physics3D
Physics3D = {}

---@param origin Vector3
---@param direction Vector3
---@param distance number
---@param layer_mask integer?
---@return RaycastHit3D
function Physics3D.raycast(origin, direction, distance, layer_mask) end

---@param origin Vector3
---@param direction Vector3
---@param distance number
---@param layer_mask integer?
---@return RaycastHit3D[]
function Physics3D.raycast_all(origin, direction, distance, layer_mask) end

-- Audio
---@class Audio
Audio = {}

---@param clip AudioClip
---@param volume number?
function Audio.play_oneshot(clip, volume) end

---@return number
function Audio.get_master_volume() end

---@param volume number
function Audio.set_master_volume(volume) end

-- EntitySpawner
---@class EntitySpawner
EntitySpawner = {}

---@param space string?
---@return Entity
function EntitySpawner.spawn_entity(space) end

---@param entity Entity
function EntitySpawner.destroy_entity(entity) end

function EntitySpawner.clear() end

---@param id integer
---@return Entity
function EntitySpawner.get_entity(id) end

---@param func fun(entity: Entity)
---@param until_predicate (fun(entity: Entity): boolean)?
function EntitySpawner.for_each_entity(func, until_predicate) end

-- Scripts
---@class Scripts
Scripts = {}

---@param relative_path string
---@return boolean
function Scripts.run_engine_file(relative_path) end

---@param relative_path string
---@param excludes string[]?
---@return boolean
function Scripts.run_engine_folder(relative_path, excludes) end

---@param relative_path string
---@return boolean
function Scripts.run_project_file(relative_path) end

---@param relative_path string
---@param excludes string[]?
---@return boolean
function Scripts.run_project_folder(relative_path, excludes) end

-- Debug
---@class Debug
Debug = {}

---@param message string
---@param color Color?
---@param duration number?
---@param log boolean?
function Debug.print(message, color, duration, log) end

---@param from Vector2
---@param to Vector2
---@param color Color?
---@param duration number?
---@param thickness number?
function Debug.draw_line(from, to, color, duration, thickness) end

---@param center Vector2
---@param radius number
---@param color Color?
---@param duration number?
---@param thickness number?
---@param segments integer?
function Debug.draw_circle(center, radius, color, duration, thickness, segments) end

---@param from Vector3
---@param to Vector3
---@param color Color?
---@param duration number?
---@param thickness number?
function Debug.draw_line_3d(from, to, color, duration, thickness) end

---@param box AABB3
---@param color Color?
---@param duration number?
---@param thickness number?
function Debug.draw_aabb3(box, color, duration, thickness) end

---@param center Vector3
---@param radius number
---@param color Color?
---@param duration number?
---@param thickness number?
---@param segments integer?
function Debug.draw_sphere_3d(center, radius, color, duration, thickness, segments) end

-- Log
---@class Log
Log = {}

---@vararg any
function Log.info(...) end

---@vararg any
function Log.error(...) end

-- BodyType
---@enum BodyType
BodyType = {
    Static = 0,
    Dynamic = 1,
    Kinematic = 2,
}

-- InputEventType
---@enum InputEventType
InputEventType = {
    Axis = 0,
    Pressed = 1,
    Released = 2,
}

-- CollisionLayer
---@enum CollisionLayer
CollisionLayer = {
    None = 0,
    Default = 1,
}

-- MotionLock
---@enum MotionLock
MotionLock = {
    None = 0,
    LinearX = 1,
    LinearY = 2,
    LinearZ = 4,
    AngularX = 8,
    AngularY = 16,
    AngularZ = 32,
    Angular = 56,
}

-- Asset
---@class Asset
local Asset = {}

---@return string
function Asset:get_name() end

---@param name string
function Asset:set_name(name) end

_G.Asset = Asset

-- Vector2
---@class Vector2
---@field x number
---@field y number
---@operator add(Vector2): Vector2
---@operator sub(Vector2): Vector2
---@operator unm: Vector2
---@operator mul(number): Vector2
---@operator div(number): Vector2
---@overload fun(): Vector2
---@overload fun(x: number, y: number): Vector2
local Vector2 = {}

---@return number
function Vector2:length() end

---@return number
function Vector2:length_sqr() end

---@return Vector2
function Vector2:normalized() end

---@return Vector2
function Vector2.zero() end

---@return Vector2
function Vector2.one() end

---@return Vector2
function Vector2.left() end

---@return Vector2
function Vector2.right() end

---@return Vector2
function Vector2.up() end

---@return Vector2
function Vector2.down() end

---@param a Vector2
---@param b Vector2
---@return number
function Vector2.dot(a, b) end

---@param a Vector2
---@param b Vector2
---@return number
function Vector2.distance(a, b) end

---@param a Vector2
---@param b Vector2
---@param t number
---@return Vector2
function Vector2.lerp(a, b, t) end

---@param point Vector2
---@param pivot Vector2
---@param radians number
---@return Vector2
function Vector2.rotate_around(point, pivot, radians) end

_G.Vector2 = Vector2

-- Vector3
---@class Vector3
---@field x number
---@field y number
---@field z number
---@operator add(Vector3): Vector3
---@operator sub(Vector3): Vector3
---@operator unm: Vector3
---@operator mul(number): Vector3
---@operator div(number): Vector3
---@overload fun(): Vector3
---@overload fun(x: number, y: number, z: number): Vector3
local Vector3 = {}

---@return number
function Vector3:length() end

---@return number
function Vector3:length_sqr() end

---@return Vector3
function Vector3:normalized() end

---@return Vector3
function Vector3.zero() end

---@return Vector3
function Vector3.one() end

---@return Vector3
function Vector3.left() end

---@return Vector3
function Vector3.right() end

---@return Vector3
function Vector3.up() end

---@return Vector3
function Vector3.down() end

---@return Vector3
function Vector3.forward() end

---@return Vector3
function Vector3.back() end

---@param a Vector3
---@param b Vector3
---@return number
function Vector3.dot(a, b) end

---@param a Vector3
---@param b Vector3
---@return Vector3
function Vector3.cross(a, b) end

---@param a Vector3
---@param b Vector3
---@return Vector3
function Vector3.scale(a, b) end

---@param a Vector3
---@param b Vector3
---@return number
function Vector3.distance(a, b) end

---@param a Vector3
---@param b Vector3
---@param t number
---@return Vector3
function Vector3.lerp(a, b, t) end

---@param a Vector3
---@param b Vector3
---@return Vector3
function Vector3.min(a, b) end

---@param a Vector3
---@param b Vector3
---@return Vector3
function Vector3.max(a, b) end

---@param a Vector3
---@return Vector3
function Vector3.abs(a) end

---@param vector Vector3
---@param plane_normal Vector3
---@return Vector3
function Vector3.project_on_plane(vector, plane_normal) end

_G.Vector3 = Vector3

-- Quaternion
---@class Quaternion
---@field x number
---@field y number
---@field z number
---@field w number
---@operator mul(Quaternion): Quaternion
---@overload fun(): Quaternion
---@overload fun(x: number, y: number, z: number, w: number): Quaternion
local Quaternion = {}

---@return Quaternion
function Quaternion:normalized() end

---@return Quaternion
function Quaternion:conjugate() end

---@return Quaternion
function Quaternion:inverse() end

---@return Vector3
function Quaternion:to_euler_deg() end

---@param vector Vector3
---@return Vector3
function Quaternion:rotate(vector) end

---@return Vector3
function Quaternion:get_forward() end

---@return Vector3
function Quaternion:get_right() end

---@return Vector3
function Quaternion:get_up() end

---@return Quaternion
function Quaternion.identity() end

---@param axis Vector3
---@param radians number
---@return Quaternion
function Quaternion.from_axis_angle(axis, radians) end

---@param euler_deg Vector3
---@return Quaternion
function Quaternion.from_euler_deg(euler_deg) end

---@param forward Vector3
---@param up Vector3?
---@return Quaternion
function Quaternion.look_rotation(forward, up) end

---@param from Vector3
---@param to Vector3
---@return Quaternion
function Quaternion.from_to_rotation(from, to) end

---@param a Quaternion
---@param b Quaternion
---@return number
function Quaternion.dot(a, b) end

---@param a Quaternion
---@param b Quaternion
---@param t number
---@return Quaternion
function Quaternion.slerp(a, b, t) end

---@param a Quaternion
---@param b Quaternion
---@return number
function Quaternion.angle_deg(a, b) end

_G.Quaternion = Quaternion

-- AABB3
---@class AABB3
---@field center Vector3
---@field extents Vector3
---@overload fun(): AABB3
---@overload fun(center: Vector3, extents: Vector3): AABB3
local AABB3 = {}

---@return Vector3
function AABB3:min() end

---@return Vector3
function AABB3:max() end

---@return Vector3
function AABB3:size() end

---@param point Vector3
---@return boolean
function AABB3:contains(point) end

---@param ray Ray
---@return number?
function AABB3:raycast(ray) end

---@param min Vector3
---@param max Vector3
---@return AABB3
function AABB3.from_min_max(min, max) end

---@param a AABB3
---@param b AABB3
---@return AABB3
function AABB3.combine(a, b) end

_G.AABB3 = AABB3

-- Ray
---@class Ray
---@field origin Vector3
---@field direction Vector3
---@overload fun(): Ray
---@overload fun(origin: Vector3, direction: Vector3): Ray
local Ray = {}

---@param distance number
---@return Vector3
function Ray:point_at(distance) end

_G.Ray = Ray

-- AABB
---@class AABB
---@field center Vector2
---@field extents Vector2
---@overload fun(): AABB
---@overload fun(center: Vector2, extents: Vector2): AABB
local AABB = {}

---@return Vector2
function AABB:min() end

---@return Vector2
function AABB:max() end

---@return Vector2
function AABB:size() end

_G.AABB = AABB

-- Capsule
---@class Capsule
---@field center_a Vector2
---@field center_b Vector2
---@field radius number
---@overload fun(): Capsule
---@overload fun(center_a: Vector2, center_b: Vector2, radius: number): Capsule
local Capsule = {}

---@return number
function Capsule:get_height() end

_G.Capsule = Capsule

-- Circle
---@class Circle
---@field center Vector2
---@field radius number
---@overload fun(): Circle
---@overload fun(center: Vector2, radius: number): Circle
local Circle = {}

_G.Circle = Circle

-- Color
---@class Color
---@field r number
---@field g number
---@field b number
---@field a number
---@overload fun(): Color
---@overload fun(r: number, g: number, b: number): Color
---@overload fun(r: number, g: number, b: number, a: number): Color
local Color = {}

---@return Color
function Color.black() end

---@return Color
function Color.white() end

---@return Color
function Color.gray() end

---@return Color
function Color.red() end

---@return Color
function Color.green() end

---@return Color
function Color.blue() end

---@return Color
function Color.yellow() end

---@return Color
function Color.magenta() end

---@return Color
function Color.cyan() end

---@return Color
function Color.orange() end

_G.Color = Color

-- Entity
---@class Entity
local Entity = {}

---@return integer
function Entity:get_id() end

---@return string
function Entity:get_name() end

---@param name string
function Entity:set_name(name) end

---@return string
function Entity:get_prefab_name() end

---@param name string
function Entity:set_prefab_name(name) end

---@return boolean
function Entity:is_valid() end

---@return boolean
function Entity:is_in_play() end

---@return boolean
function Entity:is_ticking() end

---@param ticking boolean
function Entity:set_ticking(ticking) end

---@param class_name string
---@return LuaComponent?
function Entity:add_lua_component(class_name) end

---@return TransformComponent?
function Entity:get_transform() end

---@return TransformComponent3D?
function Entity:get_transform_3d() end

---@return string
function Entity:get_space() end

---@return RigidbodyComponent?
function Entity:get_rigidbody() end

---@return CharacterBodyComponent?
function Entity:get_character_body() end

---@return BoxColliderComponent?
function Entity:get_box_collider() end

---@return CharacterBodyComponent3D?
function Entity:get_character_body_3d() end

---@return RigidbodyComponent3D?
function Entity:get_rigidbody_3d() end

---@return BoxColliderComponent3D?
function Entity:get_box_collider_3d() end

---@return SphereColliderComponent3D?
function Entity:get_sphere_collider_3d() end

---@return CapsuleColliderComponent3D?
function Entity:get_capsule_collider_3d() end

---@return CapsuleColliderComponent?
function Entity:get_capsule_collider() end

---@return CircleColliderComponent?
function Entity:get_circle_collider() end

---@return InputComponent?
function Entity:get_input() end

---@return SpriteComponent?
function Entity:get_sprite() end

---@return SpriteAnimatorComponent?
function Entity:get_sprite_animator() end

---@return SocketsComponent?
function Entity:get_sockets() end

---@return CameraComponent?
function Entity:get_camera() end

---@return CameraComponent3D?
function Entity:get_camera_3d() end

---@return DirectionalLightComponent?
function Entity:get_directional_light() end

---@return MeshRendererComponent?
function Entity:get_mesh_renderer() end

---@return AudioComponent?
function Entity:get_audio() end

---@param class_name string
---@return LuaComponent?
function Entity:get_lua_component(class_name) end

---@return LuaComponent[]
function Entity:get_lua_components() end

---@return Component[]
function Entity:get_components() end

---@param func fun(component: Component)
---@param until_predicate (fun(component: Component): boolean)?
function Entity:for_each_component(func, until_predicate) end

---@return RigidbodyComponent3D?
function Entity:add_rigidbody_3d() end

---@return BoxColliderComponent3D?
function Entity:add_box_collider_3d() end

---@return SphereColliderComponent3D?
function Entity:add_sphere_collider_3d() end

---@return CapsuleColliderComponent3D?
function Entity:add_capsule_collider_3d() end

---@return CharacterBodyComponent3D?
function Entity:add_character_body_3d() end

---@return DirectionalLightComponent?
function Entity:add_directional_light() end

---@return CameraComponent3D?
function Entity:add_camera_3d() end

---@return MeshRendererComponent?
function Entity:add_mesh_renderer() end

---@return RigidbodyComponent?
function Entity:add_rigidbody() end

---@return CharacterBodyComponent?
function Entity:add_character_body() end

---@return BoxColliderComponent?
function Entity:add_box_collider() end

---@return CapsuleColliderComponent?
function Entity:add_capsule_collider() end

---@return CircleColliderComponent?
function Entity:add_circle_collider() end

---@return InputComponent?
function Entity:add_input() end

---@return SpriteComponent?
function Entity:add_sprite() end

---@return SpriteAnimatorComponent?
function Entity:add_sprite_animator() end

---@return SocketsComponent?
function Entity:add_sockets() end

---@return CameraComponent?
function Entity:add_camera() end

---@return AudioComponent?
function Entity:add_audio() end

_G.Entity = Entity

-- Component
---@class Component
local Component = {}

---@return Entity
function Component:get_entity() end

_G.Component = Component

-- TransformComponent
---@class TransformComponent : Component
local TransformComponent = {}

---@return Vector2
function TransformComponent:get_position() end

---@param position Vector2
function TransformComponent:set_position(position) end

---@return number
function TransformComponent:get_rotation() end

---@param radians number
function TransformComponent:set_rotation(radians) end

---@return Vector2
function TransformComponent:get_scale() end

---@param scale Vector2
function TransformComponent:set_scale(scale) end

---@return Vector2
function TransformComponent:get_local_position() end

---@param position Vector2
function TransformComponent:set_local_position(position) end

---@return number
function TransformComponent:get_local_rotation() end

---@param radians number
function TransformComponent:set_local_rotation(radians) end

---@return Vector2
function TransformComponent:get_local_scale() end

---@param scale Vector2
function TransformComponent:set_local_scale(scale) end

---@return TransformComponent?
function TransformComponent:get_parent() end

---@param parent TransformComponent?
---@param keep_world_transform boolean?
function TransformComponent:set_parent(parent, keep_world_transform) end

---@return TransformComponent[]
function TransformComponent:get_children() end

---@return boolean
function TransformComponent:get_interpolate_physics() end

---@param value boolean
function TransformComponent:set_interpolate_physics(value) end

_G.TransformComponent = TransformComponent

-- TransformComponent3D
---@class TransformComponent3D : Component
local TransformComponent3D = {}

---@return Vector3
function TransformComponent3D:get_position() end

---@param position Vector3
function TransformComponent3D:set_position(position) end

---@return Quaternion
function TransformComponent3D:get_rotation() end

---@param rotation Quaternion
function TransformComponent3D:set_rotation(rotation) end

---@return Vector3
function TransformComponent3D:get_euler_deg() end

---@param euler_deg Vector3
function TransformComponent3D:set_euler_deg(euler_deg) end

---@return Vector3
function TransformComponent3D:get_lossy_scale() end

---@return Vector3
function TransformComponent3D:get_local_position() end

---@param position Vector3
function TransformComponent3D:set_local_position(position) end

---@return Quaternion
function TransformComponent3D:get_local_rotation() end

---@param rotation Quaternion
function TransformComponent3D:set_local_rotation(rotation) end

---@return Vector3
function TransformComponent3D:get_local_euler_deg() end

---@param euler_deg Vector3
function TransformComponent3D:set_local_euler_deg(euler_deg) end

---@return Vector3
function TransformComponent3D:get_local_scale() end

---@param scale Vector3
function TransformComponent3D:set_local_scale(scale) end

---@return Vector3
function TransformComponent3D:get_forward() end

---@return Vector3
function TransformComponent3D:get_right() end

---@return Vector3
function TransformComponent3D:get_up() end

---@return TransformComponent3D?
function TransformComponent3D:get_parent() end

---@param parent TransformComponent3D?
---@param keep_world_transform boolean?
function TransformComponent3D:set_parent(parent, keep_world_transform) end

---@return TransformComponent3D[]
function TransformComponent3D:get_children() end

---@return boolean
function TransformComponent3D:get_interpolate_physics() end

---@param value boolean
function TransformComponent3D:set_interpolate_physics(value) end

_G.TransformComponent3D = TransformComponent3D

-- RigidbodyComponent3D
---@class RigidbodyComponent3D : Component
local RigidbodyComponent3D = {}

---@return boolean
function RigidbodyComponent3D:has_body() end

---@return boolean
function RigidbodyComponent3D:is_awake() end

---@return BodyType
function RigidbodyComponent3D:get_body_type() end

---@param body_type BodyType
function RigidbodyComponent3D:set_body_type(body_type) end

---@return integer
function RigidbodyComponent3D:get_motion_locks() end

---@param locks integer
function RigidbodyComponent3D:set_motion_locks(locks) end

---@return number
function RigidbodyComponent3D:get_gravity_scale() end

---@param value number
function RigidbodyComponent3D:set_gravity_scale(value) end

---@return number
function RigidbodyComponent3D:get_linear_damping() end

---@param value number
function RigidbodyComponent3D:set_linear_damping(value) end

---@return number
function RigidbodyComponent3D:get_angular_damping() end

---@param value number
function RigidbodyComponent3D:set_angular_damping(value) end

---@return Vector3
function RigidbodyComponent3D:get_velocity() end

---@param velocity Vector3
function RigidbodyComponent3D:set_velocity(velocity) end

---@return Vector3
function RigidbodyComponent3D:get_angular_velocity() end

---@param angular_velocity Vector3
function RigidbodyComponent3D:set_angular_velocity(angular_velocity) end

---@return Vector3
function RigidbodyComponent3D:get_position() end

---@param position Vector3
function RigidbodyComponent3D:set_position(position) end

---@return Quaternion
function RigidbodyComponent3D:get_rotation() end

---@param rotation Quaternion
function RigidbodyComponent3D:set_rotation(rotation) end

---@param force Vector3
function RigidbodyComponent3D:apply_force(force) end

---@param impulse Vector3
function RigidbodyComponent3D:apply_impulse(impulse) end

---@param torque Vector3
function RigidbodyComponent3D:apply_torque(torque) end

_G.RigidbodyComponent3D = RigidbodyComponent3D

-- ColliderComponent3D
---@class ColliderComponent3D : Component
local ColliderComponent3D = {}

---@return number
function ColliderComponent3D:get_density() end

---@param density number
function ColliderComponent3D:set_density(density) end

---@return number
function ColliderComponent3D:get_friction() end

---@param friction number
function ColliderComponent3D:set_friction(friction) end

---@return number
function ColliderComponent3D:get_bounciness() end

---@param bounciness number
function ColliderComponent3D:set_bounciness(bounciness) end

---@return integer
function ColliderComponent3D:get_collision_layer() end

---@param layer integer
function ColliderComponent3D:set_collision_layer(layer) end

---@return integer
function ColliderComponent3D:get_collision_mask() end

---@param mask integer
function ColliderComponent3D:set_collision_mask(mask) end

---@return boolean
function ColliderComponent3D:is_trigger() end

---@param trigger boolean
function ColliderComponent3D:set_trigger(trigger) end

_G.ColliderComponent3D = ColliderComponent3D

-- BoxColliderComponent3D
---@class BoxColliderComponent3D : ColliderComponent3D
local BoxColliderComponent3D = {}

---@return AABB3
function BoxColliderComponent3D:get_box() end

---@param box AABB3
function BoxColliderComponent3D:set_box(box) end

---@return AABB3
function BoxColliderComponent3D:get_scaled_box() end

_G.BoxColliderComponent3D = BoxColliderComponent3D

-- SphereColliderComponent3D
---@class SphereColliderComponent3D : ColliderComponent3D
local SphereColliderComponent3D = {}

---@return Vector3
function SphereColliderComponent3D:get_center() end

---@param center Vector3
function SphereColliderComponent3D:set_center(center) end

---@return number
function SphereColliderComponent3D:get_radius() end

---@param radius number
function SphereColliderComponent3D:set_radius(radius) end

---@return number
function SphereColliderComponent3D:get_scaled_radius() end

_G.SphereColliderComponent3D = SphereColliderComponent3D

-- CapsuleColliderComponent3D
---@class CapsuleColliderComponent3D : ColliderComponent3D
local CapsuleColliderComponent3D = {}

---@return Vector3
function CapsuleColliderComponent3D:get_center() end

---@param center Vector3
function CapsuleColliderComponent3D:set_center(center) end

---@return number
function CapsuleColliderComponent3D:get_radius() end

---@param radius number
function CapsuleColliderComponent3D:set_radius(radius) end

---@return number
function CapsuleColliderComponent3D:get_height() end

---@param height number
function CapsuleColliderComponent3D:set_height(height) end

_G.CapsuleColliderComponent3D = CapsuleColliderComponent3D

-- CharacterBodyComponent3D
---@class CharacterBodyComponent3D : Component
local CharacterBodyComponent3D = {}

---@return Vector3
function CharacterBodyComponent3D:get_center() end

---@param center Vector3
function CharacterBodyComponent3D:set_center(center) end

---@return number
function CharacterBodyComponent3D:get_radius() end

---@param radius number
function CharacterBodyComponent3D:set_radius(radius) end

---@return number
function CharacterBodyComponent3D:get_height() end

---@param height number
function CharacterBodyComponent3D:set_height(height) end

---@return integer
function CharacterBodyComponent3D:get_collision_layer() end

---@param layer integer
function CharacterBodyComponent3D:set_collision_layer(layer) end

---@return integer
function CharacterBodyComponent3D:get_collision_mask() end

---@param mask integer
function CharacterBodyComponent3D:set_collision_mask(mask) end

---@return integer
function CharacterBodyComponent3D:get_solver_ignore_mask() end

---@param mask integer
function CharacterBodyComponent3D:set_solver_ignore_mask(mask) end

---@return number
function CharacterBodyComponent3D:get_max_slope_deg() end

---@param degrees number
function CharacterBodyComponent3D:set_max_slope_deg(degrees) end

---@param velocity Vector3
---@param fixed_dt number
function CharacterBodyComponent3D:move_and_slide(velocity, fixed_dt) end

---@return boolean
function CharacterBodyComponent3D:is_on_floor() end

---@return Vector3
function CharacterBodyComponent3D:get_floor_normal() end

---@return Vector3
function CharacterBodyComponent3D:get_velocity() end

---@param velocity Vector3
function CharacterBodyComponent3D:set_velocity(velocity) end

---@return Vector3
function CharacterBodyComponent3D:get_position() end

---@param position Vector3
function CharacterBodyComponent3D:set_position(position) end

---@return Quaternion
function CharacterBodyComponent3D:get_rotation() end

---@param rotation Quaternion
function CharacterBodyComponent3D:set_rotation(rotation) end

_G.CharacterBodyComponent3D = CharacterBodyComponent3D

-- DirectionalLightComponent
---@class DirectionalLightComponent : Component
local DirectionalLightComponent = {}

---@return Color
function DirectionalLightComponent:get_color() end

---@param color Color
function DirectionalLightComponent:set_color(color) end

---@return number
function DirectionalLightComponent:get_intensity() end

---@param intensity number
function DirectionalLightComponent:set_intensity(intensity) end

---@return Color
function DirectionalLightComponent:get_sky_color() end

---@param color Color
function DirectionalLightComponent:set_sky_color(color) end

---@return Color
function DirectionalLightComponent:get_ground_color() end

---@param color Color
function DirectionalLightComponent:set_ground_color(color) end

---@return number
function DirectionalLightComponent:get_fog_density() end

---@param density number
function DirectionalLightComponent:set_fog_density(density) end

---@return number
function DirectionalLightComponent:get_fog_height() end

---@param height number
function DirectionalLightComponent:set_fog_height(height) end

---@return number
function DirectionalLightComponent:get_fog_falloff() end

---@param falloff number
function DirectionalLightComponent:set_fog_falloff(falloff) end

---@return number
function DirectionalLightComponent:get_fog_anisotropy() end

---@param anisotropy number
function DirectionalLightComponent:set_fog_anisotropy(anisotropy) end

---@return Color
function DirectionalLightComponent:get_fog_color() end

---@param color Color
function DirectionalLightComponent:set_fog_color(color) end

---@return Vector3
function DirectionalLightComponent:get_direction() end

_G.DirectionalLightComponent = DirectionalLightComponent

-- CameraComponent3D
---@class CameraComponent3D : Component
local CameraComponent3D = {}

---@return number
function CameraComponent3D:get_fov_deg() end

---@param value number
function CameraComponent3D:set_fov_deg(value) end

---@return number
function CameraComponent3D:get_near_plane() end

---@param value number
function CameraComponent3D:set_near_plane(value) end

---@return number
function CameraComponent3D:get_far_plane() end

---@param value number
function CameraComponent3D:set_far_plane(value) end

---@param world_pos Vector3
---@return Vector2?
function CameraComponent3D:world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Ray
function CameraComponent3D:screen_to_ray(screen_pos) end

_G.CameraComponent3D = CameraComponent3D

-- MeshRendererComponent
---@class MeshRendererComponent : Component
local MeshRendererComponent = {}

---@return Mesh?
function MeshRendererComponent:get_mesh() end

---@param mesh Mesh|nil
function MeshRendererComponent:set_mesh(mesh) end

---@return Material?
function MeshRendererComponent:get_material() end

---@return Material?
function MeshRendererComponent:get_material_const() end

---@param material Material|nil
function MeshRendererComponent:set_material(material) end

---@return AABB3
function MeshRendererComponent:get_local_bounds() end

---@return AABB3
function MeshRendererComponent:get_world_bounds() end

_G.MeshRendererComponent = MeshRendererComponent

-- RigidbodyComponent
---@class RigidbodyComponent : Component
local RigidbodyComponent = {}

---@return BodyType
function RigidbodyComponent:get_body_type() end

---@param body_type BodyType
function RigidbodyComponent:set_body_type(body_type) end

---@return boolean
function RigidbodyComponent:has_fixed_rotation() end

---@param fixed boolean
function RigidbodyComponent:set_fixed_rotation(fixed) end

---@return Vector2
function RigidbodyComponent:get_velocity() end

---@param velocity Vector2
function RigidbodyComponent:set_velocity(velocity) end

---@return Vector2
function RigidbodyComponent:get_position() end

---@param position Vector2
function RigidbodyComponent:set_position(position) end

---@return number
function RigidbodyComponent:get_rotation() end

---@param radians number
function RigidbodyComponent:set_rotation(radians) end

_G.RigidbodyComponent = RigidbodyComponent

-- CharacterBodyComponent
---@class CharacterBodyComponent : Component
local CharacterBodyComponent = {}

---@return integer
function CharacterBodyComponent:get_collision_layer() end

---@param layer integer
function CharacterBodyComponent:set_collision_layer(layer) end

---@return integer
function CharacterBodyComponent:get_collision_mask() end

---@param mask integer
function CharacterBodyComponent:set_collision_mask(mask) end

---@return integer
function CharacterBodyComponent:get_solver_ignore_mask() end

---@param mask integer
function CharacterBodyComponent:set_solver_ignore_mask(mask) end

---@return Capsule
function CharacterBodyComponent:get_capsule() end

---@param capsule Capsule
function CharacterBodyComponent:set_capsule(capsule) end

---@param velocity Vector2
---@param fixed_dt number
function CharacterBodyComponent:move_and_slide(velocity, fixed_dt) end

---@return Vector2
function CharacterBodyComponent:get_velocity() end

---@param velocity Vector2
function CharacterBodyComponent:set_velocity(velocity) end

---@return Vector2
function CharacterBodyComponent:get_position() end

---@param position Vector2
function CharacterBodyComponent:set_position(position) end

---@return number
function CharacterBodyComponent:get_rotation() end

---@param radians number
function CharacterBodyComponent:set_rotation(radians) end

_G.CharacterBodyComponent = CharacterBodyComponent

-- ColliderComponent
---@class ColliderComponent : Component
local ColliderComponent = {}

---@return number
function ColliderComponent:get_density() end

---@param density number
function ColliderComponent:set_density(density) end

---@return number
function ColliderComponent:get_friction() end

---@param friction number
function ColliderComponent:set_friction(friction) end

---@return number
function ColliderComponent:get_bounciness() end

---@param bounciness number
function ColliderComponent:set_bounciness(bounciness) end

---@return integer
function ColliderComponent:get_collision_layer() end

---@param layer integer
function ColliderComponent:set_collision_layer(layer) end

---@return integer
function ColliderComponent:get_collision_mask() end

---@param mask integer
function ColliderComponent:set_collision_mask(mask) end

---@return boolean
function ColliderComponent:is_trigger() end

---@param trigger boolean
function ColliderComponent:set_trigger(trigger) end

_G.ColliderComponent = ColliderComponent

-- BoxColliderComponent
---@class BoxColliderComponent : ColliderComponent
local BoxColliderComponent = {}

---@return AABB
function BoxColliderComponent:get_aabb() end

---@param aabb AABB
function BoxColliderComponent:set_aabb(aabb) end

---@return AABB
function BoxColliderComponent:get_scaled_aabb() end

_G.BoxColliderComponent = BoxColliderComponent

-- CapsuleColliderComponent
---@class CapsuleColliderComponent : ColliderComponent
local CapsuleColliderComponent = {}

---@return Capsule
function CapsuleColliderComponent:get_capsule() end

---@param capsule Capsule
function CapsuleColliderComponent:set_capsule(capsule) end

---@return Capsule
function CapsuleColliderComponent:get_scaled_capsule() end

_G.CapsuleColliderComponent = CapsuleColliderComponent

-- CircleColliderComponent
---@class CircleColliderComponent : ColliderComponent
local CircleColliderComponent = {}

---@return Circle
function CircleColliderComponent:get_circle() end

---@param circle Circle
function CircleColliderComponent:set_circle(circle) end

---@return Circle
function CircleColliderComponent:get_scaled_circle() end

_G.CircleColliderComponent = CircleColliderComponent

-- InputComponent
---@class InputComponent : Component
local InputComponent = {}

---@param name string
---@param fn fun(value: number)
---@return integer
function InputComponent:bind_axis(name, fn) end

---@param name string
---@param id integer
function InputComponent:unbind_axis(name, id) end

---@param name string
---@param type InputEventType
---@param fn fun()
---@return integer
function InputComponent:bind_action(name, type, fn) end

---@param name string
---@param id integer
function InputComponent:unbind_action(name, id) end

function InputComponent:clear_all_bindings() end

_G.InputComponent = InputComponent

-- SpriteComponent
---@class SpriteComponent : Component
local SpriteComponent = {}

---@return Texture?
function SpriteComponent:get_texture() end

---@param path_or_texture string|Texture|nil
function SpriteComponent:set_texture(path_or_texture) end

function SpriteComponent:clear_texture() end

---@return Material?
function SpriteComponent:get_material() end

---@return Material?
function SpriteComponent:get_material_const() end

---@param material Material|nil
function SpriteComponent:set_material(material) end

---@return Vector2
function SpriteComponent:get_pivot() end

---@param pivot Vector2
function SpriteComponent:set_pivot(pivot) end

---@return Vector2
function SpriteComponent:get_scale() end

---@param scale Vector2
function SpriteComponent:set_scale(scale) end

---@return integer
function SpriteComponent:get_z_index() end

---@param z_index integer
function SpriteComponent:set_z_index(z_index) end

---@return integer
function SpriteComponent:get_pixels_per_meter() end

---@param value integer
function SpriteComponent:set_pixels_per_meter(value) end

_G.SpriteComponent = SpriteComponent

-- AnimationClip
---@class AnimationClip : Asset
---@overload fun(config: table): AnimationClip
local AnimationClip = {}

---@return number
function AnimationClip:get_duration() end

---@return boolean
function AnimationClip:get_looping() end

_G.AnimationClip = AnimationClip

-- SpriteAnimatorComponent
---@class SpriteAnimatorComponent : Component
local SpriteAnimatorComponent = {}

---@param name string
---@param clip AnimationClip?
function SpriteAnimatorComponent:add_clip(name, clip) end

function SpriteAnimatorComponent:clear_clips() end

---@param name string
function SpriteAnimatorComponent:set_default_clip(name) end

---@return string
function SpriteAnimatorComponent:get_default_clip() end

---@return string
function SpriteAnimatorComponent:get_current_clip() end

---@param name string
function SpriteAnimatorComponent:play(name) end

function SpriteAnimatorComponent:resume() end

function SpriteAnimatorComponent:pause() end

function SpriteAnimatorComponent:stop() end

---@return boolean
function SpriteAnimatorComponent:is_playing() end

---@return table<string, AnimationClip>
function SpriteAnimatorComponent:get_clips() end

---@param clips table<string, AnimationClip>
function SpriteAnimatorComponent:set_clips(clips) end

_G.SpriteAnimatorComponent = SpriteAnimatorComponent

-- SocketsComponent
---@class SocketsComponent : Component
local SocketsComponent = {}

---@param name string
---@return TransformComponent?
function SocketsComponent:get_socket(name) end

---@param name string
---@return boolean
function SocketsComponent:has_socket(name) end

---@param sockets table<string, { position: Vector2, rotation: number }>
function SocketsComponent:set_sockets(sockets) end

_G.SocketsComponent = SocketsComponent

-- CameraComponent
---@class CameraComponent : Component
local CameraComponent = {}

---@return integer
function CameraComponent:get_pixels_per_meter() end

---@param value integer
function CameraComponent:set_pixels_per_meter(value) end

---@return number
function CameraComponent:get_zoom() end

---@param multiplier number
function CameraComponent:set_zoom(multiplier) end

---@param world_pos Vector2
---@return Vector2
function CameraComponent:world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Vector2
function CameraComponent:screen_to_world(screen_pos) end

_G.CameraComponent = CameraComponent

-- AudioComponent
---@class AudioComponent : Component
local AudioComponent = {}

function AudioComponent:play() end

function AudioComponent:stop() end

---@return boolean
function AudioComponent:is_playing() end

---@return AudioClip?
function AudioComponent:get_clip() end

---@param clip AudioClip|nil
function AudioComponent:set_clip(clip) end

---@return number
function AudioComponent:get_volume() end

---@param volume number
function AudioComponent:set_volume(volume) end

---@return boolean
function AudioComponent:is_looping() end

---@param looping boolean
function AudioComponent:set_looping(looping) end

---@return boolean
function AudioComponent:is_spatial() end

---@param spatial boolean
function AudioComponent:set_spatial(spatial) end

---@return number
function AudioComponent:get_max_distance() end

---@param max_distance number
function AudioComponent:set_max_distance(max_distance) end

---@return boolean
function AudioComponent:get_autoplay() end

---@param autoplay boolean
function AudioComponent:set_autoplay(autoplay) end

_G.AudioComponent = AudioComponent

-- Texture
---@class Texture : Asset
---@overload fun(config: table): Texture
local Texture = {}

---@return integer
function Texture:get_width() end

---@return integer
function Texture:get_height() end

---@return string
function Texture:get_path() end

_G.Texture = Texture

-- Shader
---@class Shader : Asset
---@overload fun(config: table): Shader
local Shader = {}

_G.Shader = Shader

-- Material
---@class Material : Asset
---@overload fun(config: table): Material
local Material = {}

---@param name string
---@return any
function Material:get_param(name) end

---@param name string
---@param value any
function Material:set_param(name, value) end

---@return Material?
function Material:clone() end

_G.Material = Material

-- Mesh
---@class Mesh : Asset
---@overload fun(config: table): Mesh
local Mesh = {}

---@return string
function Mesh:get_source() end

---@return AABB3
function Mesh:get_bounds() end

---@return integer
function Mesh:get_vertex_count() end

---@return integer
function Mesh:get_index_count() end

_G.Mesh = Mesh

-- RaycastHit
---@class RaycastHit
---@field collider ColliderComponent?
---@field point Vector2
---@field normal Vector2
---@field distance number
---@field hit boolean
---@field entity Entity?
local RaycastHit = {}

_G.RaycastHit = RaycastHit

-- RaycastHit3D
---@class RaycastHit3D
---@field collider ColliderComponent3D?
---@field point Vector3
---@field normal Vector3
---@field distance number
---@field hit boolean
---@field entity Entity?
local RaycastHit3D = {}

_G.RaycastHit3D = RaycastHit3D

-- AudioClip
---@class AudioClip : Asset
---@overload fun(config: table): AudioClip
local AudioClip = {}

---@return string
function AudioClip:get_path() end

_G.AudioClip = AudioClip

