---@meta
-- AUTO-GENERATED by LuaPathSchemaRegistry. Do not edit by hand.
-- Source of truth: hob:: bind_path_schema(...) calls in lua_bind_assets.cpp.

--- Assigning `DefineAsset.Foo = "path/under/assets"` registers a
--- named alias for a Asset path. Reference it as `Assets.Foo` in prefabs and config; the lookup is deferred
--- and resolved at dispatch time, so DefineAsset calls can live in any file in any load order.
--- When passing `Assets.Foo` directly to a C++ setter, unwrap with `unwrap_def(...)`.
---@class DefineAsset
DefineAsset = {}

--- Registry of Asset aliases declared via `DefineAsset`. `Assets.Foo` returns a deferred reference
--- that resolves to the registered path via unwrap_def (see content/engine/scripts/unwrap.lua).
---@class Assets
Assets = {}

