---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_factory_aliases_meta. Do not edit by hand.
-- Source of truth: `DefineX.Foo = { ... }` assignments throughout scripts/.
-- Declares the `X` registry classes (e.g. Materials, AnimationClips) and adds
-- `---@field` entries so editors autocomplete `Materials.Foo`, etc.

---@class AnimationClips
---@field PlayerIdle AnimationClip
---@field PlayerRun AnimationClip

---@class Shaders
---@field Distort Shader
---@field Outline Shader
---@field Psychedelic Shader

---@class Materials
---@field BlueOutline Material
---@field Distort Material
---@field GreenOutline Material
---@field Psychedelic Material
---@field RedOutline Material
---@field WhiteOutline Material

