---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_path_aliases_meta. Do not edit by hand.
-- Source of truth: `DefineX.Foo = "..."` assignments throughout scripts/.
-- Adds `---@field` entries to each registry class (Textures, Shaders, Assets, ...)
-- so editors autocomplete `Textures.Foo`, etc. LuaCATS merges these into the
-- registry classes declared in path_schemas_meta.generated.lua.

---@class Assets

---@class Textures
---@field PlayerIdle01 string
---@field PlayerIdle02 string
---@field PlayerIdle03 string
---@field PlayerIdle04 string
---@field PlayerRun01 string
---@field PlayerRun02 string
---@field PlayerRun03 string
---@field PlayerRun04 string
---@field PlayerRun05 string
---@field PlayerRun06 string
---@field PlayerRun07 string
---@field PlayerRun08 string
---@field PlayerRun09 string
---@field PlayerRun10 string
---@field WhiteRect string

---@class Shaders
---@field Psychedelic string

