---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_path_aliases_meta. Do not edit by hand.
-- Source of truth: `DefineX.Foo = "..."` assignments throughout scripts/.
-- Adds `---@field` entries to each registry class (Textures, Shaders, Assets, ...)
-- so editors autocomplete `Textures.Foo`, etc. LuaCATS merges these into the
-- registry classes declared in path_schemas_meta.generated.lua.

---@class Assets

