---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_asset_names_meta. Do not edit by hand.
-- Source of truth: `DefineX.Foo = { ... }` assignments throughout the project.
-- Declares the `X` asset factory classes (e.g. Materials, AnimationClips) and adds
-- `---@field` entries so editors autocomplete `Materials.Foo`, etc.

---@class AnimationClips
---@field player_idle AnimationClip
---@field player_run AnimationClip

---@class Textures
---@field HJ_idle01 Texture
---@field HJ_idle02 Texture
---@field HJ_idle03 Texture
---@field HJ_idle04 Texture
---@field HJ_run01 Texture
---@field HJ_run010 Texture
---@field HJ_run02 Texture
---@field HJ_run03 Texture
---@field HJ_run04 Texture
---@field HJ_run05 Texture
---@field HJ_run06 Texture
---@field HJ_run07 Texture
---@field HJ_run08 Texture
---@field HJ_run09 Texture
---@field distort_noise Texture
---@field white_circle Texture
---@field white_rect Texture

---@class Shaders
---@field distort Shader
---@field outline Shader
---@field psychedelic Shader

---@class Materials
---@field distort Material
---@field outline_blue Material
---@field outline_cyan Material
---@field outline_green Material
---@field outline_red Material
---@field outline_white Material
---@field psychedelic Material
---@field tint_cyan Material
---@field tint_green Material
---@field tint_orange Material

---@class Meshes

---@class AudioClips
---@field whoosh_single AudioClip

