---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_component_registry_meta. Do not edit by hand.
-- Source of truth: `DefineComponent.Foo = { ... }` assignments throughout scripts/.
-- Declares the `Components` registry class and adds `---@field` entries so
-- editors autocomplete `Components.Foo`.

---@class Components
---@field Character string
---@field ContactLogger string
---@field EnemyHealthbar string
---@field Player string
Components = {}
