---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_entity_registry_meta. Do not edit by hand.
-- Source of truth: `DefineEntity.Foo = { ... }` assignments throughout scripts/.
-- Declares the `Entities` registry class and adds `---@field` entries so
-- editors autocomplete `Entities.Foo`.

---@class Entities
---@field Camera string
---@field DynamicBox string
---@field DynamicCircle string
---@field Enemy string
---@field Player string
---@field StaticBox string
---@field StaticCircle string
---@field TriggerBox string
---@field TriggerCircle string
Entities = {}
