-- AUTO-GENERATED by LuaAssetFactorySchemaRegistry. Do not edit by hand.
-- Source of truth: hob:: bind_asset_factory_schema(...) calls in lua_bind_*.cpp.

__asset_factory_schemas = {
    AnimationClips = {
        define = "DefineAnimationClip",
        lua_type = "AnimationClip",
        fields = {
            { name = "textures" },
            { name = "fps" },
            { name = "looping" },
            { name = "tracks" },
            { name = "duration" },
        },
    },
    Textures = {
        define = "DefineTexture",
        lua_type = "Texture",
        fields = {
            { name = "path" },
            { name = "wrap" },
            { name = "filter" },
        },
    },
    Shaders = {
        define = "DefineShader",
        lua_type = "Shader",
        fields = {
            { name = "path" },
            { name = "blend" },
            { name = "cull" },
            { name = "defaults" },
        },
    },
    Materials = {
        define = "DefineMaterial",
        lua_type = "Material",
        fields = {
            { name = "shader" },
            { name = "textures" },
        },
    },
    AudioClips = {
        define = "DefineAudioClip",
        lua_type = "AudioClip",
        fields = {
            { name = "path" },
        },
    },
}
