DefineTexture.WhiteRect = "images/white_rect.png"

DefineTexture.PlayerIdle01 = "images/player/HJ_idle01.png"
DefineTexture.PlayerIdle02 = "images/player/HJ_idle02.png"
DefineTexture.PlayerIdle03 = "images/player/HJ_idle03.png"
DefineTexture.PlayerIdle04 = "images/player/HJ_idle04.png"

DefineTexture.PlayerRun01 = "images/player/HJ_run01.png"
DefineTexture.PlayerRun02 = "images/player/HJ_run02.png"
DefineTexture.PlayerRun03 = "images/player/HJ_run03.png"
DefineTexture.PlayerRun04 = "images/player/HJ_run04.png"
DefineTexture.PlayerRun05 = "images/player/HJ_run05.png"
DefineTexture.PlayerRun06 = "images/player/HJ_run06.png"
DefineTexture.PlayerRun07 = "images/player/HJ_run07.png"
DefineTexture.PlayerRun08 = "images/player/HJ_run08.png"
DefineTexture.PlayerRun09 = "images/player/HJ_run09.png"
DefineTexture.PlayerRun10 = "images/player/HJ_run010.png"
