#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <system_error>
#include <vector>

#include "engine/core/debug.h"
#include "engine/core/path_utils.h"
#include "lua_script_system.h"
#include "lua_script_system_impl.h"

namespace hob {
    namespace {
        std::vector<std::string> collect_table_keys(const sol::table& t) {
            std::vector<std::string> keys;
            if (!t.valid()) {
                return keys;
            }
            t.for_each([&keys](const sol::object& k, const sol::object& v) {
                if (k.is<std::string>()) {
                    keys.push_back(k.as<std::string>());
                }
            });
            std::sort(keys.begin(), keys.end());
            return keys;
        }

        std::vector<std::string> collect_table_string_values(const sol::table& t) {
            std::vector<std::string> values;
            if (!t.valid()) {
                return values;
            }
            for (std::size_t i = 1; i <= t.size(); ++i) {
                const sol::object v = t[i];
                if (v.is<std::string>()) {
                    values.push_back(v.as<std::string>());
                }
            }
            std::sort(values.begin(), values.end());
            return values;
        }

        bool write_name_registry_meta(const std::filesystem::path& out_path,
                                      const char* registry_name,
                                      const char* dumper_label,
                                      const char* source_description,
                                      const std::vector<std::string>& names) {
            std::ostringstream out;
            out << "---@meta\n";
            out << "-- AUTO-GENERATED by LuaScriptSystem::" << dumper_label << ". Do not edit by hand.\n";
            out << "-- Source of truth: " << source_description << "\n";
            out << "-- Declares the `" << registry_name << "` registry class and adds `---@field` entries so\n";
            out << "-- editors autocomplete `" << registry_name << ".Foo`.\n\n";

            out << "---@class " << registry_name << "\n";
            for (const auto& n : names) {
                out << "---@field " << n << " string\n";
            }
            out << registry_name << " = {}\n";

            std::error_code ec;
            std::filesystem::create_directories(out_path.parent_path(), ec);

            std::ofstream f(out_path, std::ios::binary | std::ios::trunc);
            if (!f) {
                return false;
            }

            const std::string str = out.str();
            f.write(str.data(), static_cast<std::streamsize>(str.size()));
            return f.good();
        }
    } // namespace

    void LuaScriptSystem::dump_bindings_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "bindings_meta.generated.lua";

        if (!m_impl->meta.write_to_file(out_path)) {
            debug::log_error("LuaScriptSystem::dump_bindings_meta: failed to write '{}'", out_path.string());
        }
    }

    void LuaScriptSystem::dump_path_schemas_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "path_schemas_meta.generated.lua";

        if (!m_impl->path_schemas.write_meta_to_file(out_path)) {
            debug::log_error("LuaScriptSystem::dump_path_schemas_meta: failed to write '{}'", out_path.string());
        }
    }

    void LuaScriptSystem::dump_path_aliases_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "path_aliases_meta.generated.lua";

        const sol::object names_obj = m_impl->lua["__path_alias_names"];
        sol::table names_by_registry = names_obj.is<sol::table>() ? names_obj.as<sol::table>() : sol::table{};

        std::ostringstream out;
        out << "---@meta\n";
        out << "-- AUTO-GENERATED by LuaScriptSystem::dump_path_aliases_meta. Do not edit by hand.\n";
        out << "-- Source of truth: `DefineX.Foo = \"...\"` assignments throughout scripts/.\n";
        out << "-- Adds `---@field` entries to each registry class (Textures, Shaders, Assets, ...)\n";
        out << "-- so editors autocomplete `Textures.Foo`, etc. LuaCATS merges these into the\n";
        out << "-- registry classes declared in path_schemas_meta.generated.lua.\n\n";

        for (const auto& s : m_impl->path_schemas.get_schemas()) {
            sol::table entry;
            if (names_by_registry.valid()) {
                const sol::object obj = names_by_registry[s.registry_name];
                if (obj.is<sol::table>()) {
                    entry = obj.as<sol::table>();
                }
            }
            const auto names = collect_table_string_values(entry);

            out << "---@class " << s.registry_name << "\n";
            for (const auto& n : names) {
                out << "---@field " << n << " string\n";
            }
            out << "\n";
        }

        std::error_code ec;
        std::filesystem::create_directories(out_path.parent_path(), ec);

        std::ofstream f(out_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            debug::log_error("LuaScriptSystem::dump_path_aliases_meta: failed to open '{}' for writing",
                             out_path.string());
            return;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        if (!f.good()) {
            debug::log_error("LuaScriptSystem::dump_path_aliases_meta: write failed for '{}'", out_path.string());
        }
    }

    void LuaScriptSystem::dump_factory_schemas_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "factory_schemas_meta.generated.lua";

        if (!m_impl->factory_schemas.write_meta_to_file(out_path)) {
            debug::log_error("LuaScriptSystem::dump_factory_schemas_meta: failed to write '{}'", out_path.string());
        }
    }

    void LuaScriptSystem::dump_factory_aliases_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "factory_aliases_meta.generated.lua";

        const sol::object names_obj = m_impl->lua["__factory_alias_names"];
        sol::table names_by_registry = names_obj.is<sol::table>() ? names_obj.as<sol::table>() : sol::table{};

        std::ostringstream out;
        out << "---@meta\n";
        out << "-- AUTO-GENERATED by LuaScriptSystem::dump_factory_aliases_meta. Do not edit by hand.\n";
        out << "-- Source of truth: `DefineX.Foo = { ... }` assignments throughout scripts/.\n";
        out << "-- Declares the `X` registry classes (e.g. Materials, AnimationClips) and adds\n";
        out << "-- `---@field` entries so editors autocomplete `Materials.Foo`, etc.\n\n";

        for (const auto& s : m_impl->factory_schemas.get_schemas()) {
            sol::table entry;
            if (names_by_registry.valid()) {
                const sol::object obj = names_by_registry[s.registry_name];
                if (obj.is<sol::table>()) {
                    entry = obj.as<sol::table>();
                }
            }
            const auto names = collect_table_string_values(entry);

            out << "---@class " << s.registry_name << "\n";
            for (const auto& n : names) {
                out << "---@field " << n << " " << s.lua_type << "\n";
            }
            out << "\n";
        }

        std::error_code ec;
        std::filesystem::create_directories(out_path.parent_path(), ec);

        std::ofstream f(out_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            debug::log_error("LuaScriptSystem::dump_factory_aliases_meta: failed to open '{}' for writing",
                             out_path.string());
            return;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        if (!f.good()) {
            debug::log_error("LuaScriptSystem::dump_factory_aliases_meta: write failed for '{}'", out_path.string());
        }
    }

    void LuaScriptSystem::dump_entity_registry_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "entity_registry_meta.generated.lua";

        const sol::object reg = m_impl->lua["__entity_prefab_registry"];
        const sol::table reg_table = reg.is<sol::table>() ? reg.as<sol::table>() : sol::table{};
        const auto names = collect_table_keys(reg_table);

        const bool ok = write_name_registry_meta(out_path,
                                                 "Entities",
                                                 "dump_entity_registry_meta",
                                                 "`DefineEntity.Foo = { ... }` assignments throughout scripts/.",
                                                 names);

        if (!ok) {
            debug::log_error("LuaScriptSystem::dump_entity_registry_meta: failed to write '{}'", out_path.string());
        }
    }

    void LuaScriptSystem::dump_component_registry_meta() {
        const std::filesystem::path out_path =
            PathUtils::get_root_path() / "scripts" / "engine" / "meta" / "component_registry_meta.generated.lua";

        // Components defined via DefineComponent end up in __component_registry after
        // __finalize_components() runs; any still-pending ones live in __component_pending.
        std::vector<std::string> names;
        {
            const sol::object reg = m_impl->lua["__component_registry"];
            if (reg.is<sol::table>()) {
                const auto ks = collect_table_keys(reg.as<sol::table>());
                names.insert(names.end(), ks.begin(), ks.end());
            }

            const sol::object pending = m_impl->lua["__component_pending"];
            if (pending.is<sol::table>()) {
                const auto ks = collect_table_keys(pending.as<sol::table>());
                names.insert(names.end(), ks.begin(), ks.end());
            }

            std::sort(names.begin(), names.end());
            names.erase(std::unique(names.begin(), names.end()), names.end());
        }

        const bool ok = write_name_registry_meta(out_path,
                                                 "Components",
                                                 "dump_component_registry_meta",
                                                 "`DefineComponent.Foo = { ... }` assignments throughout scripts/.",
                                                 names);

        if (!ok) {
            debug::log_error("LuaScriptSystem::dump_component_registry_meta: failed to write '{}'", out_path.string());
        }
    }
} // namespace hob
