#include "lua_schema_component.h"

#include <algorithm>
#include <format>
#include <fstream>
#include <ostream>
#include <sstream>

#include "engine/core/logging.h"
#include "engine/math/constants.h"
#include "lua_schema_keys.h"

namespace hob {
    namespace {
        bool field_has_metadata(const LuaComponentSchemaField& field) {
            return !field.type.empty() || !field.enum_name.empty() || field.min != field.max || field.hide_in_inspector;
        }

        bool fields_have_metadata(const std::vector<LuaComponentSchemaField>& fields) {
            return std::any_of(fields.begin(), fields.end(), field_has_metadata);
        }

        bool fields_have_reapply_exclusions(const std::vector<LuaComponentSchemaField>& fields) {
            return std::any_of(fields.begin(), fields.end(), [](const LuaComponentSchemaField& f) {
                return !f.reapply_on_hot_reload;
            });
        }

        void write_number(std::ostream& out, float value) {
            if (value == MAX_FLOAT) {
                out << "Math.MAX_FLOAT";
                return;
            }

            if (value == MIN_FLOAT) {
                out << "Math.MIN_FLOAT";
                return;
            }

            out << std::format("{}", value);
        }
    } // namespace

    void LuaComponentSchemaRegistry::add_schema(std::string key,
                                                std::string add_method,
                                                std::string get_method,
                                                std::vector<LuaComponentSchemaField> fields,
                                                std::optional<Space> space) {
        m_schemas.emplace_back(
            std::move(key), std::move(add_method), std::move(get_method), std::move(fields), std::string(), space);
    }

    void LuaComponentSchemaRegistry::add_map_schema(std::string key,
                                                    std::string add_method,
                                                    std::string get_method,
                                                    std::string map_setter,
                                                    std::optional<Space> space) {
        m_schemas.emplace_back(std::move(key),
                               std::move(add_method),
                               std::move(get_method),
                               std::vector<LuaComponentSchemaField>{},
                               std::move(map_setter),
                               space);
    }

    bool LuaComponentSchemaRegistry::write_to_file(const std::filesystem::path& full_path) const {
        std::ostringstream out;
        out << "-- AUTO-GENERATED by LuaComponentSchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob::LuaScriptSystem::bind_components().\n\n";

        out << "local schemas = {\n";
        for (const auto& s : m_schemas) {
            out << "    " << s.key << " = {\n";
            out << "        " << component_schema_key::ADD << " = \"" << s.add_method << "\",\n";
            out << "        " << component_schema_key::GET << " = \"" << s.get_method << "\",\n";
            if (s.space.has_value()) {
                out << "        " << component_schema_key::SPACE << " = \"" << space_to_key(*s.space) << "\",\n";
            }

            if (!s.map_setter.empty()) {
                out << "        " << component_schema_key::MAP_SETTER << " = \"" << s.map_setter << "\",\n";
            }
            else if (s.fields.empty()) {
                out << "        " << component_schema_key::GETTERS << " = {},\n";
                out << "        " << component_schema_key::SETTERS << " = {},\n";
                out << "        " << component_schema_key::ORDER << " = {},\n";
            }
            else {
                out << "        " << component_schema_key::GETTERS << " = {\n";
                for (const auto& f : s.fields) {
                    out << "            " << f.name << " = \"" << f.get_method << "\",\n";
                }
                out << "        },\n";

                out << "        " << component_schema_key::SETTERS << " = {\n";
                for (const auto& f : s.fields) {
                    out << "            " << f.name << " = \"" << f.set_method << "\",\n";
                }
                out << "        },\n";

                out << "        " << component_schema_key::ORDER << " = {\n";
                for (const auto& f : s.fields) {
                    out << "            \"" << f.name << "\",\n";
                }
                out << "        },\n";

                if (fields_have_metadata(s.fields)) {
                    out << "        " << component_schema_key::TYPES << " = {\n";
                    for (const auto& f : s.fields) {
                        if (!field_has_metadata(f)) {
                            continue;
                        }

                        out << "            " << f.name << " = {";
                        if (!f.type.empty()) {
                            out << " " << component_schema_key::TYPE << " = \"" << f.type << "\",";
                        }

                        if (!f.enum_name.empty()) {
                            out << " " << component_schema_key::ENUM << " = \"" << f.enum_name << "\",";
                        }

                        if (f.min != f.max) {
                            out << " " << component_schema_key::MIN << " = ";
                            write_number(out, f.min);
                            out << ", " << component_schema_key::MAX << " = ";
                            write_number(out, f.max);
                            out << ",";
                        }

                        if (f.hide_in_inspector) {
                            out << " " << component_schema_key::HIDDEN << " = true,";
                        }

                        out << " },\n";
                    }
                    out << "        },\n";
                }

                if (fields_have_reapply_exclusions(s.fields)) {
                    out << "        " << component_schema_key::REAPPLY_ON_HOT_RELOAD << " = {\n";
                    for (const auto& f : s.fields) {
                        if (!f.reapply_on_hot_reload) {
                            out << "            " << f.name << " = false,\n";
                        }
                    }
                    out << "        },\n";
                }
            }

            out << "    },\n";
        }
        out << "}\n\n";

        out << "schemas." << component_schema_key::ORDER << " = {\n";
        for (const auto& s : m_schemas) {
            out << "    \"" << s.key << "\",\n";
        }
        out << "}\n\n";

        out << "_G.__component_schemas = schemas\n";

        std::error_code ec;
        std::filesystem::create_directories(full_path.parent_path(), ec);

        std::ofstream f(full_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            log::lua.error("LuaComponentSchemaRegistry: failed to open '{}' for writing", full_path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }
} // namespace hob
