#include "lua_schema_path.h"

#include <fstream>
#include <sstream>

#include "engine/core/logging.h"

namespace hob {
    void LuaPathSchemaRegistry::add_schema(LuaPathSchemaInfo info) {
        m_schemas.push_back(std::move(info));
    }

    const std::vector<LuaPathSchemaInfo>& LuaPathSchemaRegistry::get_schemas() const {
        return m_schemas;
    }

    bool LuaPathSchemaRegistry::write_to_file(const std::filesystem::path& full_path) const {
        std::ostringstream out;
        out << "-- AUTO-GENERATED by LuaPathSchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob:: bind_path_schema(...) calls in lua_bind_assets.cpp.\n\n";

        out << "_G.__path_schemas = {\n";
        for (const auto& s : m_schemas) {
            out << "    { registry = \"" << s.registry_name << "\""
                << ", define = \"" << s.define_name << "\""
                << ", type_label = \"" << s.type_label << "\" },\n";
        }
        out << "}\n";

        std::error_code ec;
        std::filesystem::create_directories(full_path.parent_path(), ec);

        std::ofstream f(full_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            log::lua.error("LuaPathSchemaRegistry: failed to open '{}' for writing", full_path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }

    bool LuaPathSchemaRegistry::write_meta_to_file(const std::filesystem::path& full_path) const {
        std::ostringstream out;
        out << "---@meta\n";
        out << "-- AUTO-GENERATED by LuaPathSchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob:: bind_path_schema(...) calls in lua_bind_assets.cpp.\n\n";

        for (const auto& s : m_schemas) {
            out << "--- Assigning `" << s.define_name << ".Foo = \"path/under/assets\"` registers a\n";
            out << "--- named alias for a " << s.type_label << " path. Reference it as `" << s.registry_name
                << ".Foo` in prefabs and config; the lookup is deferred\n";
            out << "--- and resolved at dispatch time, so " << s.define_name
                << " calls can live in any file in any load order.\n";
            out << "--- When passing `" << s.registry_name
                << ".Foo` directly to a C++ setter, unwrap with `unwrap_def(...)`.\n";
            out << "---@class " << s.define_name << "\n";
            out << s.define_name << " = {}\n\n";

            out << "--- Registry of " << s.type_label << " aliases declared via `" << s.define_name << "`. `"
                << s.registry_name << ".Foo` returns a deferred reference\n";
            out << "--- that resolves to the registered path via unwrap_def (see content/engine/scripts/unwrap.lua).\n";
            out << "---@class " << s.registry_name << "\n";
            out << s.registry_name << " = {}\n\n";
        }

        std::error_code ec;
        std::filesystem::create_directories(full_path.parent_path(), ec);

        std::ofstream f(full_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            log::lua.error("LuaPathSchemaRegistry: failed to open '{}' for writing", full_path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }
} // namespace hob
