#include "lua_schema_factory.h"

#include <fstream>
#include <sstream>

#include "engine/core/logging.h"

namespace hob {
    void LuaFactorySchemaRegistry::add_schema(LuaFactorySchemaInfo info) {
        m_schemas.push_back(std::move(info));
    }

    const std::vector<LuaFactorySchemaInfo>& LuaFactorySchemaRegistry::get_schemas() const {
        return m_schemas;
    }

    bool LuaFactorySchemaRegistry::write_to_file(const std::filesystem::path& full_path) const {
        std::ostringstream out;
        out << "-- AUTO-GENERATED by LuaFactorySchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob:: bind_factory_schema(...) calls in lua_bind_*.cpp.\n\n";

        out << "_G.__factory_schemas = {\n";
        for (const auto& s : m_schemas) {
            out << "    " << s.registry_name << " = {\n";
            out << "        define = \"" << s.define_name << "\",\n";
            out << "        lua_type = \"" << s.lua_type << "\",\n";

            if (s.fields.empty()) {
                out << "        fields = {},\n";
            }
            else {
                out << "        fields = {\n";
                for (const auto& f : s.fields) {
                    out << "            { name = \"" << f.name << "\" },\n";
                }
                out << "        },\n";
            }

            out << "    },\n";
        }
        out << "}\n";

        std::error_code ec;
        std::filesystem::create_directories(full_path.parent_path(), ec);

        std::ofstream f(full_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            log::lua.error("LuaFactorySchemaRegistry: failed to open '{}' for writing", full_path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }

    bool LuaFactorySchemaRegistry::write_meta_to_file(const std::filesystem::path& full_path) const {
        std::ostringstream out;
        out << "---@meta\n";
        out << "-- AUTO-GENERATED by LuaFactorySchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob:: bind_factory_schema(...) calls in lua_bind_*.cpp.\n\n";

        for (const auto& s : m_schemas) {
            out << "--- Assigning `" << s.define_name << ".Foo = { ... }` registers a\n";
            out << "--- named " << s.lua_type << " configuration. Reference it as `" << s.registry_name
                << ".Foo` in prefabs and config; the actual " << s.lua_type << "\n";
            out << "--- is built lazily on first unwrap, so " << s.define_name
                << " calls can live in any file in any load order.\n";
            out << "--- When passing `" << s.registry_name
                << ".Foo` directly to a C++ setter, unwrap with `unwrap_def(...)`.\n";
            out << "---@class " << s.define_name << "\n";
            out << s.define_name << " = {}\n\n";

            out << "--- Registry of " << s.lua_type << " configs declared via `" << s.define_name << "`. `"
                << s.registry_name << ".Foo` returns a deferred reference\n";
            out << "--- that resolves to the built " << s.lua_type
                << " via unwrap_def (see engine/scripts/unwrap.lua).\n";
            out << "---@class " << s.registry_name << "\n";
            out << s.registry_name << " = {}\n\n";
        }

        std::error_code ec;
        std::filesystem::create_directories(full_path.parent_path(), ec);

        std::ofstream f(full_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            log::lua.error("LuaFactorySchemaRegistry: failed to open '{}' for writing", full_path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }
} // namespace hob
