#include "lua_schema_component.h"

#include <fstream>
#include <sstream>

#include "engine/core/logging.h"

namespace hob {
    void LuaComponentSchemaRegistry::add_schema(std::string key,
                                                std::string add_method,
                                                std::string get_method,
                                                std::vector<LuaComponentSchemaField> fields) {
        m_schemas.push_back({std::move(key), std::move(add_method), std::move(get_method), std::move(fields), {}});
    }

    void LuaComponentSchemaRegistry::add_map_schema(std::string key,
                                                    std::string add_method,
                                                    std::string get_method,
                                                    std::string map_setter) {
        m_schemas.push_back({std::move(key), std::move(add_method), std::move(get_method), {}, std::move(map_setter)});
    }

    bool LuaComponentSchemaRegistry::write_to_file(const std::filesystem::path& full_path) const {
        std::ostringstream out;
        out << "-- AUTO-GENERATED by LuaComponentSchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob::LuaScriptSystem::bind_components().\n\n";

        out << "local schemas = {\n";
        for (const auto& s : m_schemas) {
            out << "    " << s.key << " = {\n";
            out << "        add = \"" << s.add_method << "\",\n";
            out << "        get = \"" << s.get_method << "\",\n";

            if (!s.map_setter.empty()) {
                out << "        map_setter = \"" << s.map_setter << "\",\n";
            }
            else if (s.fields.empty()) {
                out << "        getters = {},\n";
                out << "        setters = {},\n";
            }
            else {
                out << "        getters = {\n";
                for (const auto& f : s.fields) {
                    out << "            " << f.name << " = \"" << f.get_method << "\",\n";
                }
                out << "        },\n";
                out << "        setters = {\n";
                for (const auto& f : s.fields) {
                    out << "            " << f.name << " = \"" << f.set_method << "\",\n";
                }
                out << "        },\n";
            }

            out << "    },\n";
        }
        out << "}\n\n";

        out << "schemas.__order = {\n";
        for (const auto& s : m_schemas) {
            out << "    \"" << s.key << "\",\n";
        }
        out << "}\n\n";

        out << "_G.__component_schemas = schemas\n";

        std::error_code ec;
        std::filesystem::create_directories(full_path.parent_path(), ec);

        std::ofstream f(full_path, std::ios::binary | std::ios::trunc);
        if (!f) {
            log::lua.error("LuaComponentSchemaRegistry: failed to open '{}' for writing", full_path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }
} // namespace hob
